name: Build and Deploy
run-name: ${{ gitea.actor }} is deploying the app 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # مرحله اول: دریافت کد از گیتیا به صورت دستی (بدون نیاز به اینترنت)
      - name: Manual Checkout
        run: |
          echo "Cleaning workspace..."
          rm -rf ./*
          echo "Cloning repository from internal Gitea..."
          # استفاده از توکن داخلی برای احراز هویت خودکار
          git clone https://${{ gitea.token }}@git.mrbadri.ir/${{ gitea.repository }}.git .
          # سوئیچ به آخرین کامیت پاش شده
          git checkout ${{ gitea.sha }}

      # مرحله دوم: نوشتن فایل .env از سکرت گیتیا
      - name: Inject Environment File
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        run: |
          printf '%s' "$ENV_FILE_CONTENT" > .env
          echo "Environment file written."

      # مرحله سوم: بیلد ایمیج با docker/docker-compose.prod.yml (همان مسیر make prod-build)
      - name: Build Docker Image
        run: |
          echo "Starting Docker Build..."
          docker compose -f docker/docker-compose.prod.yml build

      # مرحله چهارم: اجرای اپلیکیشن
      - name: Deploy Application
        run: |
          echo "Updating containers..."
          docker compose -f docker/docker-compose.prod.yml up -d
          echo "Deployment finished successfully!"
