"""Error codes for consistent error responses."""

# General errors
INTERNAL_ERROR = "INTERNAL_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"

# Invite errors
INVITE_NOT_FOUND = "INVITE_NOT_FOUND"
INVITE_EXPIRED = "INVITE_EXPIRED"
INVITE_ALREADY_USED = "INVITE_ALREADY_USED"
PHONE_MISMATCH = "PHONE_MISMATCH"

# Contest errors
CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND"
CONTEST_NOT_ACTIVE = "CONTEST_NOT_ACTIVE"
CONTEST_ALREADY_STARTED = "CONTEST_ALREADY_STARTED"
CONTEST_EDIT_NOT_ALLOWED = "CONTEST_EDIT_NOT_ALLOWED"

# Group errors
GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
SUBGROUP_NOT_FOUND = "SUBGROUP_NOT_FOUND"

# Leader errors
LEADER_NOT_FOUND = "LEADER_NOT_FOUND"
LEADER_NOT_APPROVED = "LEADER_NOT_APPROVED"

# Member errors
MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND"
