"""add_user_id

Revision ID: f9e958f7f332
Revises: e5a3c2d8f910
Create Date: 2026-05-14 10:46:50.381596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e958f7f332'
down_revision: Union[str, Sequence[str], None] = 'e5a3c2d8f910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bale_message', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.alter_column('bale_message', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_bale_message_user_id'), 'bale_message', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bale_message', 'user', ['user_id'], ['id'])
    op.alter_column('bale_payment', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_subscription', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscription', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bale_payment', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'bale_message', type_='foreignkey')
    op.drop_index(op.f('ix_bale_message_user_id'), table_name='bale_message')
    op.alter_column('bale_message', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('bale_message', 'user_id')
    # ### end Alembic commands ###
