"""add user table

Revision ID: 30467773703d
Revises: db303d6d9349
Create Date: 2026-05-05 15:48:11.168945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import AutoString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30467773703d'
down_revision: Union[str, Sequence[str], None] = 'db303d6d9349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'user' not in existing_tables:
        op.create_table(
            'user',
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('id', AutoString(length=36), nullable=False),
            sa.Column('mobile', AutoString(length=20), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )

    existing_indexes = {idx['name'] for idx in inspector.get_indexes('user')} if 'user' in existing_tables else set()
    if 'ix_user_id' not in existing_indexes:
        op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    if 'ix_user_mobile' not in existing_indexes:
        op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=True)

    if 'bot_users' in existing_tables:
        bot_indexes = {idx['name'] for idx in inspector.get_indexes('bot_users')}
        if 'ix_bot_users_bale_user_id' in bot_indexes:
            op.drop_index(op.f('ix_bot_users_bale_user_id'), table_name='bot_users')
        op.drop_table('bot_users')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bale_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_bot', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_users_pkey'))
    )
    op.create_index(op.f('ix_bot_users_bale_user_id'), 'bot_users', ['bale_user_id'], unique=True)
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
